---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - zip
        - unzip
        - git 
  
    - name: Install NTP on Ubuntu
      apt:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - git
        - wget
        - zip
        - unzip 

    - name: start the NTP service on CENTOS
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
  
    - name: start and enable service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present
 
    - name: Add users
      user:
        name: "{{item}}"
        state: present
        group: devops
      loop: "{{usernames}}"      
